from fastapi import FastAPI, HTTPException
from google import genai
from dotenv import load_dotenv
import os
import requests

# 🔹 Load environment variables
load_dotenv()

NEWS_API_KEY = os.getenv("NEWS_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# 🔹 Debug (check if key is loaded)
print("GEMINI KEY:", GEMINI_API_KEY)

# 🔹 Create AI client
client = genai.Client(api_key=GEMINI_API_KEY)

# 🔹 FastAPI app
app = FastAPI()


@app.get("/")
def home():
    return {"message": "API is working"}


# 🔹 Fetch news
def get_news(sector):
    try:
        url = f"https://newsapi.org/v2/everything?q={sector}&apiKey={NEWS_API_KEY}"
        response = requests.get(url)
        data = response.json()

        articles = []
        for article in data.get("articles", [])[:5]:
            articles.append(article["title"])

        return articles

    except Exception:
        raise HTTPException(status_code=500, detail="Error fetching news")


# 🔹 AI analysis
def analyze_with_ai(sector, news):
    try:
        prompt = f"""
        Analyze the {sector} sector in India using this news:

        {news}

        Provide:
        1. Market Summary
        2. Opportunities
        3. Risks
        4. Conclusion
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return response.text

    except Exception as e:
        print("ERROR:", e)
        raise HTTPException(status_code=500, detail="AI analysis failed")


# 🔹 Markdown formatter
def format_markdown(sector, ai_text):
    return f"""
# 📊 {sector.upper()} Sector Analysis

## 📰 Market Summary
{ai_text}

---
Generated by AI
"""


# 🔹 Main API
# @app.get("/analyze/{sector}")
# def analyze_sector(sector: str):

#     if len(sector) < 3:
#         raise HTTPException(status_code=400, detail="Invalid sector")

#     news = get_news(sector)
#     ai_analysis = analyze_with_ai(sector, news)
#     report = format_markdown(sector, ai_analysis)

#     return {"report": report}

@app.get("/analyze/{sector}")
def analyze_sector(sector: str):

    if len(sector) < 3:
        raise HTTPException(status_code=400, detail="Invalid sector")

    news = get_news(sector)
    ai_analysis = analyze_with_ai(sector, news)
    report = format_markdown(sector, ai_analysis)

    # 🔹 Save to .md file
    filename = f"{sector}_analysis.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)

    return {
        "message": f"Report saved as {filename}",
        "report": report
    }